Phase_SNV: true

samples:
    - CKCG-00200
    - CKCG-00201
    - CKCG-00202
    
sr_fastqs:
    CKCG-00200:
                - test_data/CKCG-00200/CKCG-00200-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00200/CKCG-00200-WGS.fastp.R2.fastq.gz
    CKCG-00201:
                - test_data/CKCG-00201/CKCG-00201-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00201/CKCG-00201-WGS.fastp.R2.fastq.gz
    CKCG-00202:
                - test_data/CKCG-00202/CKCG-00201-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00202/CKCG-00201-WGS.fastp.R2.fastq.gz

lr_zmw_fastqs:
    CKCG-00200:
                - /storage/yangjianLab/wangyifei/project/01.CKCG/03.CCS+CLR/result/pbccs/${sample}/${sample}.pbccs_all.merge.fastq.gz


reference:
    CHM13:
        /storage/yangjianLab/wangyifei/resource/Reference/CHM13/chm13v2.0_maskedY_rCRS.fasta
    GRCh38:
        /storage/yangjianLab/wangyifei/resource/Reference/GRCh38/GRCh38_no_alt_analysis_set.fasta

genetic_map: "/storage/yangjianLab/wangyifei/resource/genetic_map/chm13_liftover/shapeit4/genetic_map_chm13_{chr}.reform.txt"

topmed_east_asian: "/storage/yangjianLab/wangyifei/resource/TOPMed/east_asian/merge_vcf/{chr}/TOPMed_WGS_freeze.8.east_asian.merge.{chr}.filter.snps.liftover_chm13.shapeit4.vcf.gz",

prefix:
    1kcp




#if no "merge_merfin_filter_vcf" key, default input will be c3_merge_snv/merfin/merge/CKCG.CHM13.consensus.phase1.call_set.hwe_missing_filter.vcf.gz
merge_merfin_filter_vcf: ""

#if no "sr_scaffold_vcf" key, default input will be c3_merge_snv/callset/srs_lrs_compare/CKCG.analysis_set.call_set.consensus.srs_scaffold.vcf.gz
sr_scaffold_vcf: ""

# Please standardize the paths of all samples to the same format, with only the sample names differing, and use the "{sample}" wildcard as a placeholder.
#if no "zmw_bam" key, default input will be c2_call_lr_snv/lr_mapping/{sample}/{sample}.zmw.pbmm2.bam
zmw_bam: ""


