Phase_SNV: true

samples:
    test_data/samples.list
    
sr_fastqs:
    - test_data/{sample}/{sample}.sr.R1.fastq.gz
    - test_data/{sample}/{sample}.sr.R2.fastq.gz

lr_hifi_fastqs:
    - test_data/{sample}/{sample}.lr_hifi.fastq.gz

lr_zmw_fastqs:
    - test_data/{sample}/{sample}.lr_zmw.fastq.gz

reference:
    CHM13:
        test/reference/chm13v2.0_maskedY_rCRS.fasta

genetic_map: "test/genetic_map/genetic_map_chm13_{chr}.reform.txt"

prefix:
    test


#if no "merge_merfin_filter_vcf" key, default input will be c3_merge_snv/merfin/merge/CKCG.CHM13.consensus.phase1.call_set.hwe_missing_filter.vcf.gz
merge_merfin_filter_vcf: ""

# Please standardize the paths of all samples to the same format, with only the sample names differing, and use the "{sample}" wildcard as a placeholder.
#if no "zmw_bam" key, default input will be c2_call_lr_snv/lr_mapping/{sample}/{sample}.zmw.pbmm2.bam
zmw_bam: ""


