samples:
    - CKCG-00200
    - CKCG-00201
    - CKCG-00202
    
training_samples:
    - CKCG-00202
    
test_samples:
    - CKCG-00202
    
sr_fastqs:
    CKCG-00200:
                - test_data/CKCG-00200/CKCG-00200-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00200/CKCG-00200-WGS.fastp.R2.fastq.gz
    CKCG-00201:
                - test_data/CKCG-00201/CKCG-00201-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00201/CKCG-00201-WGS.fastp.R2.fastq.gz
    CKCG-00202:
                - test_data/CKCG-00202/CKCG-00201-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00202/CKCG-00201-WGS.fastp.R2.fastq.gz
lr_hifi_fastqs:
    CKCG-00200:
                - /storage/yangjianLab/wangyifei/project/01.CKCG/03.CCS+CLR/result/pbccs/${sample}/${sample}.pbccs_all.Q20.success.fastq.gz

lr_zmw_fastqs:
    CKCG-00200:
                - /storage/yangjianLab/wangyifei/project/01.CKCG/03.CCS+CLR/result/pbccs/${sample}/${sample}.pbccs_all.merge.fastq.gz


reference:
    CHM13:
        /storage/yangjianLab/wangyifei/resource/Reference/CHM13/chm13v2.0_maskedY_rCRS.fasta
    GRCh38:
        /storage/yangjianLab/wangyifei/resource/Reference/GRCh38/GRCh38_no_alt_analysis_set.fasta

GATK_Resource:
    dbsnp:
        /storage/yangjianLab/wangyifei/resource/gatk_bundle/CHM13/chm13v2.0_dbSNPv155.vcf.gz 
    hapmap:
        /storage/yangjianLab/wangyifei/resource/gatk_bundle/CHM13/hapmap_3.3.chm13_liftover.vcf.gz 
    omni:
        /storage/yangjianLab/wangyifei/resource/gatk_bundle/CHM13/1000G_omni2.5.chm13_liftover.vcf.gz
    1000G:
        /storage/yangjianLab/wangyifei/resource/gatk_bundle/CHM13/1000G_phase1.snps.high_confidence.chm13_liftover.vcf.gz
    known_indel:
        /storage/yangjianLab/wangyifei/resource/gatk_bundle/CHM13/Homo_sapiens_assembly38.known_indels.chm13_liftover.vcf.gz 
    mills:
        /storage/yangjianLab/wangyifei/resource/gatk_bundle/CHM13/Mills_and_1000G_gold_standard.indels.chm13_liftover.vcf.gz 
    axiomPoly:
        /storage/yangjianLab/wangyifei/resource/gatk_bundle/CHM13/Axiom_Exome_Plus.genotypes.all_populations.poly.chm13_liftover.vcf.gz


genetic_map: "/storage/yangjianLab/wangyifei/resource/genetic_map/chm13_liftover/shapeit4/genetic_map_chm13_{chr}.reform.txt"

topmed_east_asian: "/storage/yangjianLab/wangyifei/resource/TOPMed/east_asian/merge_vcf/{chr}/TOPMed_WGS_freeze.8.east_asian.merge.{chr}.filter.snps.liftover_chm13.shapeit4.vcf.gz",

prefix:
    1kcp


**(1) call_sr_snv**



```shell
snakemake -s Snakefile --cores 64 --configfile config/config.yaml --configfile config/tools.yaml --configfile config/SR_var_calling.yaml
```

**(1) call_lr_snv**



```shell
snakemake -s Snakefile --cores 64 --configfile config/config.yaml --configfile config/tools.yaml --configfile config/LR_var_calling.yaml
```

**(1) merge_snv**



```shell
snakemake -s Snakefile --cores 64 --configfile config/config.yaml --configfile config/tools.yaml --configfile config/merge_snv.yaml
```

**(1) phase_snv**



```shell
snakemake -s Snakefile --cores 64 --configfile config/config.yaml --configfile config/tools.yaml --configfile config/phase_snv.yaml
```

**(1) generate_personal_reference**



```shell
snakemake -s Snakefile --cores 64 --configfile config/config.yaml --configfile config/tools.yaml --configfile config/generate_personal_reference.yaml
```

**(1) draft_assembly**



```shell
snakemake -s Snakefile --cores 64 --configfile config/config.yaml --configfile config/tools.yaml --configfile config/draft_assembly.yaml
```

**(1) split_minigraph**



```shell
snakemake -s Snakefile --cores 64 --configfile config/config.yaml --configfile config/tools.yaml --configfile config/split_minigraph.yaml
```

**(1) graph_construction**



```shell
snakemake -s Snakefile --cores 64 --configfile config/config.yaml --configfile config/tools.yaml --configfile config/graph_construction.yaml
```

**(1) simplify_ml_pangenome**



```shell
snakemake -s Snakefile --cores 64 --configfile config/config.yaml --configfile config/tools.yaml --configfile config/simplify_ml_pangenome.yaml
```

**(1) merge_pangenome**



```shell
snakemake -s Snakefile --cores 64 --configfile config/config.yaml --configfile config/tools.yaml --configfile config/merge_pangenome.yaml
```

**(1) infer_diploid_path**



```shell
snakemake -s Snakefile --cores 64 --configfile config/config.yaml --configfile config/tools.yaml --configfile config/infer_diploid_path.yaml
```