Draft_Assembly: true

samples:
    - CKCG-00200
    - CKCG-00201
    - CKCG-00202

    
sr_fastqs:
    CKCG-00200:
                - test_data/CKCG-00200/CKCG-00200-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00200/CKCG-00200-WGS.fastp.R2.fastq.gz
    CKCG-00201:
                - test_data/CKCG-00201/CKCG-00201-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00201/CKCG-00201-WGS.fastp.R2.fastq.gz
    CKCG-00202:
                - test_data/CKCG-00202/CKCG-00201-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00202/CKCG-00201-WGS.fastp.R2.fastq.gz

lr_zmw_fastqs:
    CKCG-00200:
                - /storage/yangjianLab/wangyifei/project/01.CKCG/03.CCS+CLR/result/pbccs/${sample}/${sample}.pbccs_all.merge.fastq.gz


reference:
    CHM13:
        /storage/yangjianLab/wangyifei/resource/Reference/CHM13/chm13v2.0_maskedY_rCRS.fasta

        
prefix:
    1kcp
    
pac: "/storage/yangjianLab/wangyifei/project/01.CKCG/03.CCS+CLR/sample.list"



#if no "consensus_fasta" key, default input will be “c5_personal_ref/consensus_fasta/{sample}/CHM13.af_pangenome.{sample}_polish.fasta”
consensus_fasta: 

#if no "chain" key, default input will be "c5_personal_ref/consensus_fasta/{sample}/CHM13.af_pangenome.{sample}_polish.chain"
chain: 

#if no "sample_vcf" key, default input will be "c4_phase_snv/shapeit4/samples/{sample}/{sample}.shapeit4.vcf.gz"
sample_vcf: 

#if no "sample_WGS_meryl" key, default input will be "c3_merge_snv/meryl/{sample}/{sample}-WGS.meryl" (directory)
sample_WGS_meryl: 
    
