Split_Minigraph: true

samples:
    - CKCG-00200
    - CKCG-00201
    - CKCG-00202

    
sr_fastqs:
    CKCG-00200:
                - test_data/CKCG-00200/CKCG-00200-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00200/CKCG-00200-WGS.fastp.R2.fastq.gz
    CKCG-00201:
                - test_data/CKCG-00201/CKCG-00201-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00201/CKCG-00201-WGS.fastp.R2.fastq.gz
    CKCG-00202:
                - test_data/CKCG-00202/CKCG-00201-WGS.fastp.R1.fastq.gz
                - test_data/CKCG-00202/CKCG-00201-WGS.fastp.R2.fastq.gz

lr_zmw_fastqs:
    CKCG-00200:
                - /storage/yangjianLab/wangyifei/project/01.CKCG/03.CCS+CLR/result/pbccs/${sample}/${sample}.pbccs_all.merge.fastq.gz


reference:
    CHM13:
        /storage/yangjianLab/wangyifei/resource/Reference/CHM13/chm13v2.0_maskedY_rCRS.fasta
    GRCh38:
        /storage/yangjianLab/wangyifei/resource/Reference/GRCh38/GRCh38_no_alt_analysis_set.fasta

        
prefix:
    1kcp


#if no "hap1_adaptor_masked_fa" key, default input will be "c6_draft_assembly/{sample}/assembly/{sample}.hap1.adaptor_masked.fasta"
hap1_adaptor_masked_fa: 

#if no "hap2_adaptor_masked_fa" key, default input will be "c6_draft_assembly/{sample}/assembly/{sample}.hap2.adaptor_masked.fasta"
hap2_adaptor_masked_fa: 
    
